### ISSUE TITLE
Mongo DB insert does not work with mongo java driver version 3.1.1

### ISSUE THREAD

**Issue by sumatipatri** [pentaho/pentaho-mongodb-plugin#113]
Error i found i am attaching here..

[test - MongoDB Output] INFO org.mongodb.driver.connection - Opened connection [connectionId{localValue:2, serverValue:8}] to localhost:27017
java.lang.NoSuchMethodError: com.mongodb.WriteResult.getLastError()Lcom/mongodb/CommandResult;
	at org.pentaho.di.trans.steps.mongodboutput.MongoDbOutput.doBatch(MongoDbOutput.java:339)
	at org.pentaho.di.trans.steps.mongodboutput.MongoDbOutput.processRow(MongoDbOutput.java:211)
	at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
	at java.lang.Thread.run(Thread.java:744)
